all:
  hosts:
    ad-root:
      ansible_host: 10.180.25.25
      ansible_user: ansible
      ansible_password: QWErty1.2.3.4.5
      ansible_connection: winrm
      ansible_winrm_transport: kerberos
      ansible_winrm_server_cert_validation: ignore
