---

- name: install NuGet
  win_shell: Install-PackageProvider -Name Nuget -Force

- name: Create temp folder
  win_shell: new-item C:\Temp -itemtype directory
  ignore_errors: yes

- name: change DNS server
  when: not ansible_windows_domain_member
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: "{{ hostvars[groups['ad-user'][0]]['groups']['ad-user'] }}"

- name: Deploy ComputerManagementDsc module
  win_psmodule:
    name: ComputerManagementDsc
    state: present

- name: Add computer to domain
  win_dsc:
    resource_name: Computer
    Name: 'user-desktop1'
    DomainName:  "{{ user_domain_name }}.{{ root_domain_name }}"
    Credential_username: "{{ user_dom_admin_username }}@{{ user_domain_name }}.{{ root_domain_name }}"
    Credential_password: "{{ user_dom_admin_password }}"
  register: userserver

- name: reboot after domain joined
  win_reboot:
  when: userserver.reboot_required

- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900